#!/bin/sh
# Creates a 2D axisymmetrical geometry in the form of a 3D wedge with a small angle
# Compatible with OpenFOAM v6.0+

# 21/08/2019: use the conventions for a multiphase simulation

cd ${0%/*} || exit 1                        # Run from this directory
rm -r constant/polyMesh
gmsh -3 cyl_annulus_valve.geo -o cyl_multi.msh
gmshToFoam cyl_multi.msh
checkMesh
python3 rename_multiphase.py ## Automatically rename wall and wedge patches
